//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlines_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string TicketId { get; set; }
        public string FlightId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AgeGroup { get; set; }
        public string SourceId { get; set; }
        public string DestinationId { get; set; }
        public System.TimeSpan DepartTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string SeatNo { get; set; }
        public System.DateTime DateTravel { get; set; }
        public string Class { get; set; }
        public decimal Price { get; set; }
        public string BookingId { get; set; }
        public Nullable<System.DateTime> DateCancellation { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
